<?php
/**
 * @category    Olts
 * @package     Olts_Reminder
 * @author      Olena Tsareva <olts@ciklum.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/* @var $this Olts_Reminder_Block_Adminhtml_Notification */
?>

<?php foreach ($this->getReminders() as $reminder): ?>
    <div class="notification-global notification-global-notice">
        <?php echo $reminder->getTitle() ?>
    </div>
<?php endforeach; ?>